In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Analisis de indicadores estadisticos

## Indicadores de tendencia central, dispersión y posición

## *cálculos en arrays*

In [2]:
import numpy as np

In [4]:
a = np.array([4, 5, 9, 4, 6, 3, 2])
a

array([4, 5, 9, 4, 6, 3, 2])

In [5]:
np.sum(a)
np.mean(a)
np.median(a)

import statistics as stat
stat.mode(a)

33

4.714285714285714

4.0

4

In [7]:
np.percentile(a, 25) # del 100% de datos de a, el 25% de datos tiene valores menores a 3.5, y el 75% tiene valores mayores a 3.5
np.percentile(a, 50) # del 100% de datos de a, el 50% de datos tiene valores menores a 4, y el 50% tiene valores mayores a 4
np.percentile(a, 75) # del 100% de datos de a, el 75% de datos tiene valores menores a 5.5, y el 25% tiene valores mayores a 5.5

3.5

4.0

5.5

In [8]:
# a = array([4, 5, 9, 4, 6, 3, 2])

min(a)
max(a)
np.std(a)

2

9

2.1189138534559038

In [9]:
from scipy.stats import skew
from scipy.stats import kurtosis

skew(a)
kurtosis(a)

0.8274271039321606

-0.1402479338842988

In [10]:
np.random.seed(2021)
a = np.random.randint(1, 9, size=(3, 3))
a

array([[5, 6, 2],
       [1, 6, 7],
       [7, 5, 8]])

In [11]:
np.sum(a)
np.sum(a, 0) # por columnas
np.sum(a, 1) # por filas

47

array([13, 17, 17])

array([13, 14, 20])

In [12]:
np.mean(a)
np.mean(a, 0) # por columnas
np.mean(a, 1) # por filas

5.222222222222222

array([4.33333333, 5.66666667, 5.66666667])

array([4.33333333, 4.66666667, 6.66666667])

In [13]:
np.std(a)
np.std(a, 0) # por columnas
np.std(a, 1) # por filas

2.199887763691481

array([2.49443826, 0.47140452, 2.62466929])

array([1.69967317, 2.62466929, 1.24721913])

In [14]:
# array([[5, 6, 2],
#       [1, 6, 7],
#       [7, 5, 8]])

np.percentile(a, 25)
np.percentile(a, 25, 0) # por columnas
np.percentile(a, 25, 1) # por filas

5.0

array([3. , 5.5, 4.5])

array([3.5, 3.5, 6. ])

In [15]:
a.min()
a.min(0) # por columnas
a.min(1) # por filas

1

array([1, 5, 2])

array([2, 1, 5])

In [16]:
a.max()
a.max(0) # por columnas
a.max(1) # por filas

8

array([7, 6, 8])

array([6, 7, 8])

## *cálculos en dataframes*

In [4]:
import pandas as pd

In [6]:
import os
os.getcwd()
# os.chdir('C:\\Users\\caleb.terrel\\Desktop\\2-Python_para_analisis_exploratorio_de_datos\\datasets')
# os.getcwd()
os.chdir('F:\\Cursos\\ENPP\\2-Python_para_analisis_exploratorio_de_datos\\datasets')

'F:\\Cursos\\ENPP\\2-Python_para_analisis_exploratorio_de_datos\\codigos python'

In [7]:
ed = pd.read_excel('EmployeeData2.xlsx')
ed.head()

id    sexo    fechnac  educ          catlab  salario  salini  tiempemp  \
0   1  Hombre 1952-02-03    15       Directivo    57000   27000        98   
1   2  Hombre 1958-05-23    16  Administrativo    40200   18750        98   
2   3   Mujer 1929-07-26    12  Administrativo    21450   12000        98   
3   4   Mujer 1947-04-15     8  Administrativo    21900   13200        98   
4   5  Hombre 1955-02-09    15  Administrativo    45000   21000        98   

  expprev minoria  
0     144      No  
1      36      No  
2     381      No  
3     190      No  
4     138      No

In [21]:
ed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 474 entries, 0 to 473
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype         
---  ------    --------------  -----         
 0   id        474 non-null    int64         
 1   sexo      474 non-null    object        
 2   fechnac   473 non-null    datetime64[ns]
 3   educ      474 non-null    int64         
 4   catlab    474 non-null    object        
 5   salario   474 non-null    int64         
 6   salini    474 non-null    int64         
 7   tiempemp  474 non-null    int64         
 8   expprev   474 non-null    object        
 9   minoria   474 non-null    object        
dtypes: datetime64[ns](1), int64(5), object(4)
memory usage: 37.2+ KB


In [23]:
#ed.describe()
ed.describe(include = "all")

<ipython-input-23-1c2bf960d898>:2: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  ed.describe(include = "all")


id    sexo              fechnac        educ          catlab  \
count   474.000000     474                  473  474.000000             474   
unique         NaN       2                  461         NaN               3   
top            NaN  Hombre  1962-02-08 00:00:00         NaN  Administrativo   
freq           NaN     258                    2         NaN             363   
first          NaN     NaN  1929-02-10 00:00:00         NaN             NaN   
last           NaN     NaN  1971-02-10 00:00:00         NaN             NaN   
mean    237.500000     NaN                  NaN   13.491561             NaN   
std     136.976275     NaN                  NaN    2.884846             NaN   
min       1.000000     NaN                  NaN    8.000000             NaN   
25%     119.250000     NaN                  NaN   12.000000             NaN   
50%     237.500000     NaN                  NaN   12.000000             NaN   
75%     355.750000     NaN                  NaN   15.000000             NaN   
max     474.000000     NaN                  NaN   21.000000             NaN   

              salario        salini    tiempemp  expprev minoria  
count      474.000000    474.000000  474.000000      474     474  
unique            NaN           NaN         NaN      208       2  
top               NaN           NaN         NaN  Ausente      No  
freq              NaN           NaN         NaN       24     370  
first             NaN           NaN         NaN      NaN     NaN  
last              NaN           NaN         NaN      NaN     NaN  
mean     34419.567511  17016.086498   81.109705      NaN     NaN  
std      17075.661465   7870.638154   10.060945      NaN     NaN  
min      15750.000000   9000.000000   63.000000      NaN     NaN  
25%      24000.000000  12487.500000   72.000000      NaN     NaN  
50%      28875.000000  15000.000000   81.000000      NaN     NaN  
75%      36937.500000  17490.000000   90.000000      NaN     NaN  
max     135000.000000  79980.000000   98.000000      NaN     NaN

In [24]:
ed.isnull().sum()

id          0
sexo        0
fechnac     1
educ        0
catlab      0
salario     0
salini      0
tiempemp    0
expprev     0
minoria     0
dtype: int64

In [25]:
ed['sexo'].value_counts()
ed['catlab'].value_counts()

Hombre    258
Mujer     216
Name: sexo, dtype: int64

Administrativo    363
Directivo          84
Seguridad          27
Name: catlab, dtype: int64

In [26]:
ed['sexo'].value_counts(normalize=True)
ed['catlab'].value_counts(normalize=True)

Hombre    0.544304
Mujer     0.455696
Name: sexo, dtype: float64

Administrativo    0.765823
Directivo         0.177215
Seguridad         0.056962
Name: catlab, dtype: float64

### Agregacion de dataframe

In [9]:
ed.groupby(by='sexo')['salario'].mean()

sexo
Hombre    41441.782946
Mujer     26031.921296
Name: salario, dtype: float64

In [8]:
pd.DataFrame(ed.groupby(by='sexo')['salario'].mean())

salario
sexo                
Hombre  41441.782946
Mujer   26031.921296

In [12]:
pd.DataFrame(ed.groupby(by='sexo', as_index = False)['salario'].mean())

sexo       salario
0  Hombre  41441.782946
1   Mujer  26031.921296

In [10]:
ed.groupby(by=['sexo', 'catlab'])['salario'].mean()

sexo    catlab        
Hombre  Administrativo    31558.152866
        Directivo         66243.243243
        Seguridad         30938.888889
Mujer   Administrativo    25003.689320
        Directivo         47213.500000
Name: salario, dtype: float64

In [11]:
pd.DataFrame(ed.groupby(by=['sexo', 'catlab'])['salario'].mean())

salario
sexo   catlab                      
Hombre Administrativo  31558.152866
       Directivo       66243.243243
       Seguridad       30938.888889
Mujer  Administrativo  25003.689320
       Directivo       47213.500000

In [16]:
pd.DataFrame(ed.groupby(by=['sexo', 'catlab'], as_index = False)['salario'].mean())

sexo          catlab       salario
0  Hombre  Administrativo  31558.152866
1  Hombre       Directivo  66243.243243
2  Hombre       Seguridad  30938.888889
3   Mujer  Administrativo  25003.689320
4   Mujer       Directivo  47213.500000

In [17]:
# en ed selecciono las variables numericas q requiero calcular

ed[['sexo', 'catlab', 'salario', 'tiempemp']].groupby(by=['sexo', 'catlab']).agg([np.mean, np.std])

salario                 tiempemp           
                               mean           std       mean        std
sexo   catlab                                                          
Hombre Administrativo  31558.152866   7997.977675  81.726115  10.670239
       Directivo       66243.243243  18051.569628  81.770270  10.403565
       Seguridad       30938.888889   2114.616411  81.555556   8.486792
Mujer  Administrativo  25003.689320   5812.838103  80.563107   9.658228
       Directivo       47213.500000   8501.252538  76.600000   9.766155

In [19]:
# si no selecciono las variables el calculo se realizara en todas las variables numericas

ed.groupby(by=['sexo', 'catlab']).agg([np.mean, np.std])

id                   educ            \
                             mean         std       mean       std   
sexo   catlab                                                        
Hombre Administrativo  227.605096  145.068938  13.751592  2.171069   
       Directivo       225.135135  143.020099  17.418919  1.646971   
       Seguridad       233.851852  115.010268  10.185185  2.219443   
Mujer  Administrativo  246.922330  130.923973  12.194175  2.228675   
       Directivo       300.100000  131.694470  16.000000  0.000000   

                            salario                      salini               \
                               mean           std          mean          std   
sexo   catlab                                                                  
Hombre Administrativo  31558.152866   7997.977675  15861.210191  2564.693552   
       Directivo       66243.243243  18051.569628  31627.702703  9749.812860   
       Seguridad       30938.888889   2114.616411  15077.777778  1341.234602   
Mujer  Administrativo  25003.689320   5812.838103  12750.752427  2391.056414   
       Directivo       47213.500000   8501.252538  20121.000000  4252.341708   

                        tiempemp             
                            mean        std  
sexo   catlab                                
Hombre Administrativo  81.726115  10.670239  
       Directivo       81.770270  10.403565  
       Seguridad       81.555556   8.486792  
Mujer  Administrativo  80.563107   9.658228  
       Directivo       76.600000   9.766155

In [15]:
ed[['sexo', 'catlab', 'salario', 'tiempemp']].groupby(by=['sexo', 'catlab'], as_index = False).agg([np.mean, np.std])

salario                 tiempemp           
                               mean           std       mean        std
sexo   catlab                                                          
Hombre Administrativo  31558.152866   7997.977675  81.726115  10.670239
       Directivo       66243.243243  18051.569628  81.770270  10.403565
       Seguridad       30938.888889   2114.616411  81.555556   8.486792
Mujer  Administrativo  25003.689320   5812.838103  80.563107   9.658228
       Directivo       47213.500000   8501.252538  76.600000   9.766155